# Generated by Django 6.0.4 on 2026-04-12 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrators',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('admin_email', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'administrators',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Boxes',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('b_number', models.IntegerField()),
                ('b_capacity', models.IntegerField(blank=True, null=True)),
                ('b_status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'boxes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_lname', models.CharField(max_length=50)),
                ('c_fname', models.CharField(max_length=50)),
                ('c_sname', models.CharField(blank=True, max_length=50, null=True)),
                ('c_age', models.IntegerField(blank=True, null=True)),
                ('c_gender', models.CharField(blank=True, max_length=1, null=True)),
                ('c_phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('c_email', models.CharField(blank=True, max_length=50, null=True)),
                ('c_visits', models.IntegerField(blank=True, null=True)),
                ('c_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'clients',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Masters',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('m_name', models.CharField(max_length=100)),
                ('m_spec', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'masters',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(blank=True, max_length=100, null=True)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'services',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_brand', models.CharField(max_length=30)),
                ('car_model', models.CharField(max_length=30)),
                ('car_year', models.IntegerField(blank=True, null=True)),
                ('car_packet', models.CharField(blank=True, max_length=100, null=True)),
                ('car_info', models.TextField(blank=True, null=True)),
                ('car_plate', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('c', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='workshop.clients')),
            ],
            options={
                'db_table': 'cars',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('o_id', models.AutoField(primary_key=True, serialize=False)),
                ('o_datetime', models.DateTimeField()),
                ('o_status', models.CharField(blank=True, max_length=20, null=True)),
                ('b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='workshop.boxes')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='workshop.cars')),
                ('m', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='workshop.masters')),
            ],
            options={
                'db_table': 'orders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('o', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='workshop.orders')),
                ('s', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='workshop.services')),
            ],
            options={
                'db_table': 'order_details',
                'managed': True,
                'unique_together': {('o', 's')},
            },
        ),
    ]
